# -*- coding: utf-8 -*-
"""prakalgo 7 arik dias putra

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tg7bJTZNIlIkruai_VGGSTsDVj4fsBYw
"""

banner = """
@@@@ @@@@  @ @  @
@  @ @   @ @ @ @
@@@@ @  @@ @ @@
@  @ @ @   @ @ @
@  @ @  @  @ @   @

"""
print(banner)

def faktorial(x):
  if x == 0 or x == 1:
    return 1
  else:
    return x * faktorial(x - 1)

x = int(input("nilai: "))
h = faktorial(x)
print(f"Faktorial dari {x} adalah {h}")

banner = """

@@@@ @@@@  @ @  @
@  @ @   @ @ @ @
@@@@ @  @@ @ @@
@  @ @ @   @ @ @
@  @ @  @  @ @   @

"""
print(banner)

def hitung_vokal_konsonan(kalimat):
    vokal = 0
    konsonan = 0

    for huruf in kalimat:
        if huruf.lower() in 'aeiou':
            vokal += 1
        elif huruf.isalpha():
            konsonan += 1

    return vokal, konsonan

kalimat = input("Masukkan sesuatu: ")

jumlah_vokal, jumlah_konsonan = hitung_vokal_konsonan(kalimat)

print(f"Jumlah huruf vokal: {jumlah_vokal}")
print(f"Jumlah huruf konsonan: {jumlah_konsonan}")