# -*- coding: utf-8 -*-
"""PraklAlgo 6 Arik Dias Putra

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ndYM9sac5r0VdqcNtofv1Gv8V6y4aTAk
"""

# Banner Python
banner = """

@@@@ @@@@  @ @  @
@  @ @   @ @ @ @
@@@@ @  @@ @ @@
@  @ @ @   @ @ @
@  @ @  @  @ @   @

"""

# Menampilkan banner pada layar
print(banner)

print("GANJIL -> JARAK TEMPUH")
v0=float(input("masukkan v0= "))
t=float(input("masukkan t= "))
a=float(input("masukkan a= "))

s=(v0*t)+(1/2*(a*t**2))
print(f"Jika kecepatan= {v0}m/s, dengan percepatan {a}m/s^2 dan waktu= {t}s, maka jarak tempuh adalah {s} meter")

# Banner Python
banner = """

@@@@ @@@@  @ @  @
@  @ @   @ @ @ @
@@@@ @  @@ @ @@
@  @ @ @   @ @ @
@  @ @  @  @ @   @

"""

# Menampilkan banner pada layar
print(banner)

def hitung_luas():
    print("KALKULATOR MENCARI LUAS")

    while True:
        print("1. Kubus")
        print("2. Balok")
        print("3. Tabung")
        print("4. Kerucut")
        print("5. Bola")
        print("6. Keluar")

        pilihan = input("Mau yang mana: ")

        try:
            pilihan = int(pilihan)
            if pilihan not in [1, 2, 3, 4, 5, 6]:
                raise ValueError("Pilihan tidak valid.")
        except ValueError as e:
            print(e)
            continue

        if pilihan == 1:
            s = float(input("Masukkan sisi: "))
            print("sisi =", s)
            hasil = 6*s**2
            print("luas =", hasil)

        elif pilihan == 2:
            p = float(input("Masukkan panjang: "))
            l = float(input("masukkan lebar: "))
            t = float(input("Masukkan tinggi: "))
            print(f"panjang = ", p)
            print(f"lebar = ", l)
            print(f"tinggi = ", t)
            hasil = 2*((p*l)+(p*t)+(l*t))
            print("luas = ", hasil)

        elif pilihan == 3:
            r = float(input("Masukkan jari-jari: "))
            t = float(input("Masukkan tinggi: "))
            print("jari-jari = ", r)
            print("tinggi = ", t)
            hasil = 2*3.14*r*(r+t)
            print("luas = ", hasil)

        elif pilihan == 4:
            r = float(input("Masukkan jari-jari: "))
            s = float(input("Masukkan panjang garis pelukis: "))
            print("jari-jari = ", r)
            print("panjang garis pelukis = ", s)
            hasil = 3.14*r*(r+s)
            print("luas = ", hasil)

        elif pilihan == 5:
            r = float(input("Masukkan jari-jari: "))
            print("jari-jari = ", r)
            hasil = 3.14*r**2
            print("luas = ", hasil)

        else:
          break;


if __name__ == "__main__":
    hitung_luas()