# -*- coding: utf-8 -*-
"""PrakAlgo 1_Arik Dias Putra

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LuiDTwpKvYY3aDOrA9Yoh0gS20N7Q1ZQ
"""

# Banner Python
banner = """

@@@@ @@@@  @ @  @
@  @ @   @ @ @ @
@@@@ @  @@ @ @@
@  @ @ @   @ @ @
@  @ @  @  @ @   @

"""

# Menampilkan banner pada layar
print(banner)


print('Im playing genshin')
print('how "aku main valorant"')

import math

# Fungsi untuk menghitung jarak antara dua titik koordinat
def hitung_jarak(x1, y1, x2, y2):
    jarak = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)
    return jarak

# Meminta input dari pengguna
input_titik1 = input("masukkan angka pertama: ")
input_titik2 = input("masukkan angka kedua: ")

# Memisahkan input menjadi koordinat x dan y
x1, y1 = map(float, input_titik1.split())
x2, y2 = map(float, input_titik2.split())

# Menghitung jarak antara dua titik
jarak = hitung_jarak(x1, y1, x2, y2)

# Menampilkan hasil
print(f"Jarak antara titik pertama dan titik kedua adalah {jarak:.} satuan.")

# Fungsi untuk mengkapitalisasi string 4 karakter
def kapitalisasi_string(input_string):
    if len(input_string) != 4:
        return "Input harus terdiri dari tepat 4 karakter."

    kapitalisasi = ""
    for char in input_string:
        unicode_value = ord(char)

        # Memeriksa apakah karakter adalah huruf kecil
        if 97 <= unicode_value <= 122:  # Rentang kode ASCII untuk huruf kecil
            # Menambahkan 32 ke kode Unicode untuk mengubah ke huruf besar
            unicode_value -= 32

        kapitalisasi += chr(unicode_value)

    return kapitalisasi

# Meminta input dari pengguna
input_string = input("Masukkan string 4 karakter (huruf kecil): ")

# Memanggil fungsi dan menampilkan hasil
hasil_kapitalisasi = kapitalisasi_string(input_string)
print("Hasil kapitalisasi:", hasil_kapitalisasi)