# -*- coding: utf-8 -*-
"""prakalgo 7 arik dias putra

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tg7bJTZNIlIkruai_VGGSTsDVj4fsBYw
"""

banner = """
@@@@ @@@@  @ @  @
@  @ @   @ @ @ @
@@@@ @  @@ @ @@
@  @ @ @   @ @ @
@  @ @  @  @ @   @

"""
print(banner)

def faktorial(x):
  if x == 0 or x == 1:
    return 1
  else:
    return x * faktorial(x - 1)

x = int(input("nilai: "))
h = faktorial(x)
print(f"Faktorial dari {x} adalah {h}")

banner = """

@@@@ @@@@  @ @  @
@  @ @   @ @ @ @
@@@@ @  @@ @ @@
@  @ @ @   @ @ @
@  @ @  @  @ @   @

"""
print(banner)

def hitung_vokal_konsonan(kalimat):
    vokal = 0
    konsonan = 0

    for huruf in kalimat:
        if huruf.lower() in 'aeiou':
            vokal += 1
        elif huruf.isalpha():
            konsonan += 1

    return vokal, konsonan

kalimat = input("Masukkan sesuatu: ")

jumlah_vokal, jumlah_konsonan = hitung_vokal_konsonan(kalimat)

print(f"Jumlah huruf vokal: {jumlah_vokal}")
print(f"Jumlah huruf konsonan: {jumlah_konsonan}")

def hitung_kubik(angka):
    """
    Fungsi untuk mengembalikan nilai kubik dari suatu angka.

    Parameters:
    - angka (int): Angka yang akan dipangkatkan 3.

    Returns:
    - int: Nilai kubik dari angka.
    """
    return angka**3

def cek_habis_dibagi_tiga(angka):
    """
    Fungsi untuk mengecek apakah suatu angka habis dibagi 3.

    Parameters:
    - angka (int): Angka yang akan dicek.

    Returns:
    - int or str: Jika habis dibagi 3, kembalikan nilai kubik angka. Jika tidak, kembalikan "False".
    """
    if angka % 3 == 0:
        return hitung_kubik(angka)
    else:
        return "False"

# Input angka dari pengguna
angka_input = int(input("Masukkan angka: "))

# Memanggil fungsi kedua untuk mengecek dan menghitung kubik jika perlu
hasil = cek_habis_dibagi_tiga(angka_input)

# Menampilkan hasil
print(hasil)