# -*- coding: utf-8 -*-
"""PrakAlgo 5 Arik Dias Putra

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u4elDxt3fsq1tJaruE-ctZGendvszKay
"""

# Banner Python
banner = """

@@@@ @@@@  @ @  @
@  @ @   @ @ @ @
@@@@ @  @@ @ @@
@  @ @ @   @ @ @
@  @ @  @  @ @   @

"""

# Menampilkan banner pada layar
print(banner)

# Input dari pengguna
jumlah = int(input("Masukkan jumlah bilangan: "))
bilangan_pertama = int(input("Masukkan angka pertama: "))
bilangan_kedua = int(input("Masukkan angka kedua: "))

# Inisialisasi bilangan awal
a, b = bilangan_pertama, bilangan_kedua

# Menampilkan bilangan pertama dan kedua
print("berikut urutannya\n", a)
print("berikut urutannya\n", b)


# Menghasilkan deret Fibonacci
for i in range(jumlah - 2):
    a, b = b, a + b
    print("berikut urutannya\n", b)

# Banner Python
banner = """

@@@@ @@@@  @ @  @
@  @ @   @ @ @ @
@@@@ @  @@ @ @@
@  @ @ @   @ @ @
@  @ @  @  @ @   @

"""

# Menampilkan banner pada layar
print(banner)

print("=====HITUNGAN GAJI=====")

masuk = float(input("Jam masuk kantor: "))

print("Selamat pagi")

keluar = float(input("Jam keluar kantor: "))

jam_kerja = keluar - masuk

print("Selamat siang menuju sore")

print("=====Gincian Gaji Harian=====")

# jumlah jam kerja
print(f"Total jam kerja: {jam_kerja} jam")

print("Gaji harian: Rp.175000 ")

# Gaji per hari
gaji_harian = 175000  # Gaji per hari sebesar 175 ribu

# Menghitung gaji tambahan jika jam kerja lebih dari 8 jam
if jam_kerja > 8:
    jam_lebih = jam_kerja - 8
    gaji_tambahan = jam_lebih * 15000  # 15 ribu per jam
else:
    gaji_tambahan = 0

# Menghitung jam yang lebih
lebih_jam = jam_kerja - 8

# Menghitung total gaji per hari
lembur = gaji_harian + gaji_tambahan

# Menampilkan hasila
print(f"Lembur: Rp.{lembur}", (f"{lebih_jam} jam x Rp.15000"))

print(f"Total: Rp.{gaji_harian + lembur}")

print("=========TERIMAKASIH=========")