# -*- coding: utf-8 -*-
"""prakalgo 13 arik dias putra

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-B35eds8GxRu6z9nv2zQEpHn27d8TWfc
"""

# Input nilai dalam mata uang lokal (Rupiah)
nilai_rupiah = float(input("Masukkan jumlah uang dalam Rupiah: "))

# Input kurs mata uang asing terhadap mata uang lokal (1 Dolar Amerika ke Rupiah)
kurs_dolar = float(input("Masukkan kurs Dolar terhadap Rupiah: "))

# Mengonversi nilai Rupiah ke Dolar Amerika
nilai_dolar = nilai_rupiah / kurs_dolar

print(f"Jumlah uang dalam Dolar: ${nilai_dolar}")

# Input nilai siswa
nilai_siswa = []

for i in range(5):
    nilai = int(input(f"Masukkan nilai siswa {i + 1}: "))
    nilai_siswa.append(nilai)

# Menghitung nilai rata-rata
rata_rata = sum(nilai_siswa) / len(nilai_siswa)

print(f"Nilai rata-rata kelas adalah: {rata_rata}")

# Menentukan siswa yang mendapatkan nilai di atas rata-rata
siswa_diatas_rata = [nilai for nilai in nilai_siswa if nilai > rata_rata]

if siswa_diatas_rata:
    print("Nilai siswa yang di atas rata-rata:")
    print(siswa_diatas_rata)
else:
    print("Tidak ada siswa yang mendapatkan nilai di atas rata-rata.")

# Inisialisasi list untuk menyimpan informasi proyek
proyek_list = []

# Input informasi proyek
jumlah_proyek = int(input("Masukkan jumlah proyek: "))

for i in range(jumlah_proyek):
    nama_proyek = input(f"Masukkan nama proyek {i + 1}: ")
    status_proyek = input(f"Masukkan status proyek {i + 1} (dalam pengerjaan/selesai): ").lower()
    estimasi_waktu = int(input(f"Masukkan estimasi waktu penyelesaian proyek {i + 1} (dalam hari): "))

    proyek = {"Nama Proyek": nama_proyek, "Status": status_proyek, "Estimasi Waktu": estimasi_waktu}
    proyek_list.append(proyek)

# Menampilkan proyek yang masih dalam pengerjaan, diurutkan berdasarkan estimasi waktu penyelesaian
proyek_dalam_pengerjaan = [proyek for proyek in proyek_list if proyek["Status"] == "dalam pengerjaan"]
proyek_dalam_pengerjaan_sorted = sorted(proyek_dalam_pengerjaan, key=lambda x: x["Estimasi Waktu"])

print("\nProyek yang masih dalam pengerjaan, diurutkan berdasarkan estimasi waktu penyelesaian:")
for proyek in proyek_dalam_pengerjaan_sorted:
    print(f"Nama Proyek: {proyek['Nama Proyek']}, Estimasi Waktu: {proyek['Estimasi Waktu']} hari")